[tool.poetry]
name = "youtube-tdd-fast-api"
version = "0.1.0"
description = ""
authors = ["RukshanJS"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
